"use client";
import * as Dialog from "@radix-ui/react-dialog";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { AnimatePresence, motion } from "motion/react";
import { IconArrowDown, IconArrowUp, IconBroadcast, IconMicrophone, IconPlayerPlay, IconPlus, IconSearch, IconWaveSine } from "@tabler/icons-react";
import { FormEvent, useEffect, useRef, useState } from "react";

type Snapshot = { nowPlaying: Item | null; queue: Item[]; voiceNote: { status: string; durationSeconds: number } | null; viewer: { displayName: string; noteEligible: boolean } | null };
type Item = { id:string; score:number; track:{title:string;artist:string;artwork:string;durationSeconds:number;spotifyUri:string}; addedByName:string; voterHasVoted:boolean };
type PlaybackStatus = "Connect Spotify"|"Connecting"|"Ready"|"Playing"|"Paused"|"Premium required"|"Playback unavailable";
declare global { interface Window { onSpotifyWebPlaybackSDKReady?: () => void; Spotify?: { Player: new (options: any) => any } } }
function useSpotifyPlayback(uri: string | undefined) {
 const [status,setStatus]=useState<PlaybackStatus>("Connect Spotify"), [player,setPlayer]=useState<any>(null), [deviceId,setDeviceId]=useState<string>();
 const connect=()=>{ if (player) { void player.connect(); return; } setStatus("Connecting"); const start=()=>{ if (!window.Spotify) { setStatus("Playback unavailable"); return; } const next=new window.Spotify.Player({name:"Open Radio",getOAuthToken:(cb:(token:string)=>void)=>{fetch("/api/spotify/token").then(async r=>{const b=await r.json();if(!r.ok)throw Object.assign(new Error(b.error),{code:b.code});cb(b.access_token)}).catch(e=>setStatus(e.code==="SPOTIFY_ACCOUNT_ERROR"?"Premium required":"Playback unavailable"))},volume:0.8}); next.addListener("ready",({device_id}:{device_id:string})=>{setDeviceId(device_id);next._options.getOAuthToken((token:string)=>{void fetch("https://api.spotify.com/v1/me/player",{method:"PUT",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({device_ids:[device_id],play:false})}).then(r=>{if(!r.ok)throw new Error()}).catch(()=>setStatus("Playback unavailable"))});setStatus("Ready")}); next.addListener("not_ready",()=>{setDeviceId(undefined);setStatus("Playback unavailable")}); next.addListener("autoplay_failed",()=>setStatus("Paused")); next.addListener("authentication_error",()=>setStatus("Playback unavailable")); next.addListener("account_error",()=>setStatus("Premium required")); next.addListener("playback_error",()=>setStatus("Playback unavailable")); next.addListener("player_state_changed",(state:any)=>state&&setStatus(state.paused?"Paused":"Playing"));setPlayer(next);void next.connect()}; if(window.Spotify)start();else{window.onSpotifyWebPlaybackSDKReady=start;if(!document.querySelector('script[src="https://sdk.scdn.co/spotify-player.js"]')){const s=document.createElement("script");s.src="https://sdk.scdn.co/spotify-player.js";s.async=true;document.body.appendChild(s)}} };
 useEffect(()=>{if(!uri||!deviceId||!player)return;player._options.getOAuthToken((token:string)=>{void fetch(`https://api.spotify.com/v1/me/player/play?device_id=${encodeURIComponent(deviceId)}`,{method:"PUT",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({uris:[uri]})}).then(r=>{if(!r.ok)throw new Error()}).catch(()=>setStatus("Playback unavailable"))})},[uri,deviceId,player]);
 return {status,connect,play:()=>{if(status==="Connect Spotify"){window.location.assign("/api/spotify/login");return}if(status==="Paused")void player?.resume();else connect()}};
}
const json = async (url:string, init?:RequestInit) => { const r = await fetch(url, init); const body = await r.json(); if (!r.ok) throw new Error(body.error); return body; };
const duration = (seconds:number) => `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2,"0")}`;

export function Radio() {
 const client=useQueryClient(), [query,setQuery]=useState(""), [results,setResults]=useState<any[]>([]), [name,setName]=useState(""), [error,setError]=useState(""), [recording,setRecording]=useState(false); const recorder=useRef<MediaRecorder|null>(null), chunks=useRef<Blob[]>([]), started=useRef(0), recordingTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const station=useQuery<Snapshot>({ queryKey:["station"], queryFn:()=>json("/api/station"), refetchInterval:20_000 }); const snapshot=station.data;
 const refresh=()=>client.invalidateQueries({queryKey:["station"]});
 useEffect(()=>{ const es=new EventSource("/api/events"); es.addEventListener("station.changed",refresh); return()=>es.close(); },[]);
 const playback=useSpotifyPlayback(snapshot?.nowPlaying?.track.spotifyUri);
 useEffect(()=>{ const t=setTimeout(async()=>{ try { setResults((await json(`/api/search?q=${encodeURIComponent(query)}`)).tracks); } catch { setError("Search is temporarily unavailable."); } },150); return()=>clearTimeout(t); },[query]);
 const mutate=(url:string, body:any)=>json(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}).then(refresh).catch(e=>setError(e.message));
 const saveName=(e:FormEvent)=>{e.preventDefault(); mutate("/api/identity",{displayName:name});};
 const toggleRecording=async()=>{ let stream: MediaStream|undefined; try { if (!recording) { stream=await navigator.mediaDevices.getUserMedia({audio:true}); const r=new MediaRecorder(stream,{mimeType:"audio/webm;codecs=opus"}); chunks.current=[]; started.current=Date.now(); r.ondataavailable=e=>chunks.current.push(e.data); r.onstop=async()=>{ stream?.getTracks().forEach(t=>t.stop()); stream=undefined; const blob=new Blob(chunks.current,{type:"audio/webm"}); chunks.current=[]; const form=new FormData(); form.set("audio",blob,"note.webm"); form.set("duration",String((Date.now()-started.current)/1000)); try { await json("/api/notes",{method:"POST",body:form}); refresh(); } catch(e) { setError(e instanceof Error?e.message:"Recording failed"); }}; r.start(); recorder.current=r; setRecording(true); recordingTimer.current=setTimeout(()=>{ if(r.state==="recording") r.stop(); recordingTimer.current=null; },5000); } else { if(recordingTimer.current) { clearTimeout(recordingTimer.current); recordingTimer.current=null; } recorder.current?.stop(); recorder.current=null; setRecording(false); } } catch { stream?.getTracks().forEach(t=>t.stop()); setError("Microphone permission is required to record a note."); setRecording(false); } };
 return <main className="shell"><header style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:30}}><div style={{display:"flex",gap:10,alignItems:"center"}}><IconBroadcast color="var(--lime)" size={27}/><b style={{fontSize:20,letterSpacing:"-.04em"}}>OPEN RADIO</b><span className="eyebrow" style={{marginLeft:8}}>live / beta</span></div><div className="muted">{snapshot?.viewer ? `Listening as ${snapshot.viewer.displayName}` : "Anonymous listener"}</div></header>
 <section className="card" style={{padding:24,display:"grid",gridTemplateColumns:"150px 1fr auto",gap:24,alignItems:"center",marginBottom:22}}><img src={snapshot?.nowPlaying?.track.artwork ?? "/artwork.svg"} alt="" width="150" height="150" style={{borderRadius:14,background:"#182035"}}/><div><div className="eyebrow">{snapshot?.voiceNote ? "station transition · voice note" : "on air now"}</div><h1 style={{fontSize:36,margin:"7px 0"}}>{snapshot?.nowPlaying?.track.title ?? "Waiting for the first signal"}</h1><p className="muted" style={{margin:0}}>{snapshot?.nowPlaying?.track.artist ?? "Add a track to start the station"}</p><div style={{height:5,background:"#252c3d",borderRadius:99,marginTop:24,overflow:"hidden"}}><div style={{height:"100%",width:"42%",background:"var(--lime)"}}/></div></div><div className="eyebrow" style={{textAlign:"right"}}><button className="btn" style={{padding:"7px 10px",fontSize:12}} onClick={playback.play}><IconPlayerPlay size={16} style={{verticalAlign:"middle"}}/> {playback.status}</button><br/><span className="muted" style={{letterSpacing:0}}>Spotify playback is listener-specific</span></div></section>
 <div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 340px",gap:22}}><section className="card" style={{padding:22}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline"}}><div><div className="eyebrow">community sequence</div><h2 style={{margin:"5px 0 20px"}}>Up next <span className="muted" style={{fontSize:15}}>{snapshot?.queue.length ?? 0} tracks</span></h2></div><IconWaveSine color="var(--purple)"/></div><AnimatePresence initial={false}>{snapshot?.queue.map((item,index)=><motion.article layout key={item.id} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0}} style={{display:"grid",gridTemplateColumns:"28px 52px 1fr auto",gap:12,alignItems:"center",padding:"12px 0",borderTop:"1px solid #242b3b"}}><b className="muted">{String(index+1).padStart(2,"0")}</b><img src={item.track.artwork} alt="" width="52" height="52" style={{borderRadius:8}}/><div><b>{item.track.title}</b><div className="muted" style={{fontSize:13}}>{item.track.artist} · added by {item.addedByName}</div></div><div style={{display:"flex",alignItems:"center",gap:7}}><button aria-label="Upvote" disabled={item.voterHasVoted} className="icon" onClick={()=>mutate("/api/votes",{entryId:item.id,direction:"up"})}><IconArrowUp size={17}/></button><b>{item.score}</b><button aria-label="Downvote" disabled={item.voterHasVoted} className="icon" onClick={()=>mutate("/api/votes",{entryId:item.id,direction:"down"})}><IconArrowDown size={17}/></button></div></motion.article>)}</AnimatePresence>{!snapshot?.queue.length&&<p className="muted">The queue is clear. Be the first to put something on air.</p>}</section>
 <aside style={{display:"grid",gap:22}}><section className="card" style={{padding:20}}><div className="eyebrow">add to broadcast</div><h2 style={{margin:"5px 0 14px"}}>Find a track</h2><div style={{position:"relative"}}><IconSearch size={17} style={{position:"absolute",left:11,top:12,color:"var(--muted)"}}/><input className="input" style={{paddingLeft:35}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Spotify"/></div><div>{results.slice(0,4).map(track=><div key={track.id} style={{padding:"12px 0",borderBottom:"1px solid #252c3c",display:"flex",justifyContent:"space-between",gap:8}}><span><b style={{display:"block",fontSize:14}}>{track.title}</b><small className="muted">{track.artist} · {duration(track.durationSeconds)}</small></span><button className="icon" aria-label={`Queue ${track.title}`} onClick={()=>mutate("/api/queue",{trackId:track.id})}><IconPlus size={18}/></button></div>)}</div></section><section className="card" style={{padding:20}}><div className="eyebrow">between songs</div><h2 style={{margin:"5px 0 8px"}}>Voice drop</h2><p className="muted" style={{fontSize:13,marginTop:0}}>Record one five-second note after you have two tracks waiting.</p><button className="btn" disabled={!snapshot?.viewer?.noteEligible} onClick={toggleRecording}><IconMicrophone size={16} style={{verticalAlign:"middle"}}/> {recording?"Stop recording":"Record 5 sec"}</button></section></aside></div>
 <Dialog.Root open={!snapshot?.viewer}><Dialog.Portal><Dialog.Overlay style={{position:"fixed",inset:0,zIndex:40,background:"#03050dcc"}}/><Dialog.Content className="card" style={{position:"fixed",zIndex:50,width:"min(420px,calc(100vw - 36px))",left:"50%",top:"50%",transform:"translate(-50%,-50%)",padding:25}}><div className="eyebrow">welcome to the frequency</div><Dialog.Title style={{fontSize:27,margin:"7px 0"}}>What should we call you?</Dialog.Title><Dialog.Description className="muted">Your name appears beside the tracks you queue. No account required.</Dialog.Description><form onSubmit={saveName} style={{marginTop:18,display:"grid",gap:10}}><input aria-invalid={Boolean(error)} autoFocus className="input" value={name} onChange={e=>{setName(e.target.value);setError("")}} maxLength={32} placeholder="Display name"/><button className="btn">Enter station</button>{error&&<p role="alert" style={{margin:0,color:"#ff9ead",fontSize:13}}>{error}</p>}</form></Dialog.Content></Dialog.Portal></Dialog.Root>{error&&snapshot?.viewer&&<div role="alert" aria-live="assertive" style={{position:"fixed",zIndex:100,bottom:20,right:20,width:"min(420px,calc(100vw - 36px))",background:"#511e2b",border:"1px solid #e46b80",padding:"14px 16px",borderRadius:10,boxShadow:"0 12px 30px #0008"}}><b style={{display:"block",marginBottom:4}}>Couldn’t complete that</b>{error}</div>}</main>;
}
