import crypto from "node:crypto";
import { getSpotifyAccount, saveSpotifyAccount } from "@/lib/durable";

const stateCookie = "open_radio_spotify_oauth";
const stateLifetimeSeconds = 600;
const b64 = (value: Buffer) => value.toString("base64url");
function secret() { const value = process.env.SESSION_ENCRYPTION_KEY; if (!value) throw new Error("SESSION_ENCRYPTION_KEY is not configured"); return crypto.createHash("sha256").update(value).digest(); }
export function oauthCookieName() { return stateCookie; }
export function createPkce() { const verifier = b64(crypto.randomBytes(32)); const challenge = b64(crypto.createHash("sha256").update(verifier).digest()); const state = b64(crypto.randomBytes(24)); const payload = `${state}.${verifier}.${Date.now() + stateLifetimeSeconds * 1000}`; const signature = b64(crypto.createHmac("sha256", secret()).update(payload).digest()); return { state, challenge, value: `${payload}.${signature}` }; }
export function readPkce(value: string | undefined, expectedState: string) { if (!value) throw new Error("Spotify OAuth session expired"); const [state, verifier, expiry, signature] = value.split("."); const payload = `${state}.${verifier}.${expiry}`; const expected = crypto.createHmac("sha256", secret()).update(payload).digest(); let validSignature = false; try { const actual = Buffer.from(signature ?? "", "base64url"); validSignature = actual.length === expected.length && crypto.timingSafeEqual(actual, expected); } catch { validSignature = false; } if (!state || !verifier || !expiry || !signature || state !== expectedState || !Number.isFinite(Number(expiry)) || Number(expiry) < Date.now() || !validSignature) throw new Error("invalid Spotify OAuth state"); return verifier; }
export function redirectUri() { if (process.env.NODE_ENV === "production" && process.env.SPOTIFY_PRODUCTION_REDIRECT_URI) return process.env.SPOTIFY_PRODUCTION_REDIRECT_URI; return process.env.SPOTIFY_REDIRECT_URI ?? "http://127.0.0.1:3000/api/spotify/callback"; }
export function spotifyAuthorizationUrl(state: string, challenge: string) { const url = new URL("https://accounts.spotify.com/authorize"); url.search = new URLSearchParams({ client_id: required("SPOTIFY_CLIENT_ID"), response_type: "code", redirect_uri: redirectUri(), scope: "streaming user-read-email user-read-private", state, code_challenge_method: "S256", code_challenge: challenge }).toString(); return url.toString(); }
function required(name: string) { const value = process.env[name]; if (!value) throw new Error(`${name} is not configured`); return value; }
async function exchange(body: URLSearchParams) { const response = await fetch("https://accounts.spotify.com/api/token", { method: "POST", headers: { Authorization: `Basic ${Buffer.from(`${required("SPOTIFY_CLIENT_ID")}:${required("SPOTIFY_CLIENT_SECRET")}`).toString("base64")}`, "Content-Type": "application/x-www-form-urlencoded" }, body, cache: "no-store" }); if (!response.ok) throw Object.assign(new Error(response.status === 400 ? "Spotify authorization expired" : "Spotify token exchange failed"), { code: response.status === 400 ? "SPOTIFY_AUTH_EXPIRED" : "SPOTIFY_UNAVAILABLE" }); return await response.json() as { access_token: string; refresh_token?: string; expires_in: number; error?: string }; }
export async function completeLogin(userId: string, code: string, verifier: string) { const tokens = await exchange(new URLSearchParams({ grant_type: "authorization_code", code, redirect_uri: redirectUri(), code_verifier: verifier })); const me = await fetch("https://api.spotify.com/v1/me", { headers: { Authorization: `Bearer ${tokens.access_token}` }, cache: "no-store" }); if (!me.ok) throw new Error("Spotify account lookup failed"); const profile = await me.json() as { id?: string }; if (!profile.id || !tokens.refresh_token) throw new Error("Spotify did not return a refresh token"); if (!await saveSpotifyAccount({ userId, spotifyUserId: profile.id, encryptedRefreshToken: encrypt(tokens.refresh_token), tokenExpiresAt: new Date(Date.now() + tokens.expires_in * 1000) })) throw new Error("Spotify account storage is unavailable"); return tokens.access_token; }
function encrypt(value: string) { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv("aes-256-gcm", secret(), iv); const ciphertext = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return `${b64(iv)}.${b64(cipher.getAuthTag())}.${b64(ciphertext)}`; }
function decrypt(value: string) { const [iv, tag, ciphertext] = value.split("."); if (!iv || !tag || !ciphertext) throw new Error("invalid stored Spotify session"); const decipher = crypto.createDecipheriv("aes-256-gcm", secret(), Buffer.from(iv, "base64url")); decipher.setAuthTag(Buffer.from(tag, "base64url")); return Buffer.concat([decipher.update(Buffer.from(ciphertext, "base64url")), decipher.final()]).toString("utf8"); }
export async function refreshForUser(userId: string) { const account = await getSpotifyAccount(userId); if (!account) throw Object.assign(new Error("Spotify account is not connected"), { code: "SPOTIFY_NOT_CONNECTED" }); const tokens = await exchange(new URLSearchParams({ grant_type: "refresh_token", refresh_token: decrypt(account.encryptedRefreshToken) })); if (tokens.error || !tokens.access_token) throw Object.assign(new Error("Spotify authorization expired"), { code: "SPOTIFY_AUTH_EXPIRED" }); await saveSpotifyAccount({ userId, spotifyUserId: account.spotifyUserId, encryptedRefreshToken: tokens.refresh_token ? encrypt(tokens.refresh_token) : account.encryptedRefreshToken, tokenExpiresAt: new Date(Date.now() + tokens.expires_in * 1000) }); return tokens.access_token; }
