import { boolean, customType, integer, pgTable, primaryKey, text, timestamp, uuid } from "drizzle-orm/pg-core";

const bytea = customType<{ data: Uint8Array; driverData: Buffer }>({ dataType: () => "bytea", toDriver: (value) => Buffer.from(value), fromDriver: (value) => new Uint8Array(value) });

export const users = pgTable("users", { id: uuid("id").primaryKey(), displayName: text("display_name").notNull(), createdAt: timestamp("created_at").defaultNow().notNull() });
export const tracks = pgTable("tracks", { id: text("id").primaryKey(), spotifyUri: text("spotify_uri").notNull(), title: text("title").notNull(), artist: text("artist").notNull(), artwork: text("artwork").notNull(), durationSeconds: integer("duration_seconds").notNull() });
export const queueEntries = pgTable("queue_entries", { id: uuid("id").primaryKey(), trackId: text("track_id").notNull().references(() => tracks.id), userId: uuid("user_id").notNull().references(() => users.id), queuedAt: timestamp("queued_at").defaultNow().notNull(), score: integer("score").notNull().default(1), played: boolean("played").notNull().default(false) });
export const votes = pgTable("votes", { userId: uuid("user_id").notNull().references(() => users.id), queueEntryId: uuid("queue_entry_id").notNull().references(() => queueEntries.id), direction: text("direction", { enum: ["up", "down"] }).notNull() }, (table) => [primaryKey({ columns: [table.userId, table.queueEntryId] })]);
export const voiceNotes = pgTable("voice_notes", { id: uuid("id").primaryKey(), userId: uuid("user_id").notNull().references(() => users.id), audio: bytea("audio").notNull(), durationMilliseconds: integer("duration_milliseconds").notNull(), status: text("status", { enum: ["pending", "playing"] }).notNull() });
export const stationPlayback = pgTable("station_playback", { id: integer("id").primaryKey(), queueEntryId: uuid("queue_entry_id").references(() => queueEntries.id), startedAt: timestamp("started_at"), transitionEndsAt: timestamp("transition_ends_at") });
export const spotifyAccounts = pgTable("spotify_accounts", { userId: uuid("user_id").primaryKey().references(() => users.id), spotifyUserId: text("spotify_user_id").notNull(), encryptedRefreshToken: text("encrypted_refresh_token").notNull(), tokenExpiresAt: timestamp("token_expires_at").notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
